substitutions:
  name: slimmelezer-31
esphome:
  name: ${name}
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "2.0"
  on_boot:
    then:
      - if:
          condition:
            lambda: return id(has_key);
          then:
            - lambda: |-
                std::string key(id(stored_decryption_key), 32);
                id(dsmr_instance).set_decryption_key(key);
          else:
            - logger.log:
                level: info
                format: "Not using decryption key. If you need to set a key use Home Assistant service 'ESPHome:  ${device_name}_set_dsmr_key'"


wifi:
  ap:
    ssid: ${device_name}

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  services:
    service: set_dsmr_key
    variables:
      private_key: string
    then:
      - logger.log:
          format: Setting private key %s. Set to empty string to disable
          args: [private_key.c_str()]
      - globals.set:
          id: has_key
          value: !lambda "return private_key.length() == 32;"
      - lambda: |-
          if (private_key.length() == 32)
            private_key.copy(id(stored_decryption_key), 32);
          id(dsmr_instance).set_decryption_key(private_key);

ota:

dashboard_import:
  package_import_url: github://zuidwijk/dsmr/slimmelezer.yaml@main

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 1700

globals:
  - id: has_key
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: stored_decryption_key
    type: char[32]
    restore_value: yes

dsmr:
  id: dsmr_instance
  max_telegram_length: 2000

sensor:
  - platform: dsmr
    energy_delivered_lux:
      name: "Energy Consumed 31"
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_returned_lux:
      name: "Energy Produced 31"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    electricity_failures:
      name: "Electricity Failures 31"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures 31"
      icon: mdi:alert
#    voltage_l1:
#      name: "Voltage Phase 1"
#    current_l1:
#      name: "Current Phase 1"
    power_delivered_l1:
      name: "Power Consumed 31"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced 31"
      accuracy_decimals: 3
  - platform: uptime
    name: "SlimmeLezer Uptime 31"
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal 31"
    update_interval: 60s

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification 31"
    p1_version:
      name: "DSMR Version 31"
    p1_version_be:
      name: "DSMR Version 31"
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP Address 31"
    ssid:
      name: "SlimmeLezer Wi-Fi SSID 31"
    bssid:
      name: "SlimmeLezer Wi-Fi BSSID 31"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true